twitter:

  consumer_key: your_consumer_key_here
  consumer_secret:  your_consumer_secrete_her
  access_token_key: your_access_token_key_here
  access_token_secret: your_access_token_secret_here

# These are all the available options
# You dont need to uncomment all
# Just the ones you want to override

#  min_ratelimit_percent: 10

#  search:
#    queries:
#      - RT to win
#      - Retweet and win
#      - Giveaway retweet:
#        lang: en
#      - "using #hashtags need quotes"
#      - "per search options work with quotes too":
#         lang: es
#    skip_retweeted: false
#    max_queue: 100
#    max_quote_depth: 20
#    min_quote_similarity: 0.5
#    filter:
#      min_retweets:
#        enabled: false
#        number: 20
#      blacklist:
#        enabled: false
#        keywords: ["obama", "trump"]
#        users: ["BotSpotterBot"]
#    sort:
#      by_keywords:
#        enabled: true
#        keywords: ["ps4", "pc"]
#      by_age:
#        enabled: true
#      by_retweets_count:
#        enabled: true
#
#  actions:
#    follow:
#      enabled: true
#      keywords: ["follow", "follower"]
#      max_following: 1950
#      multiple: false
#    favorite:
#      enabled: true
#      keywords: ["fav", "favorite", "like"]
#    tag_friend:
#      enabled: false
#      friends: ["friend1", "friend2", "friend3"]
#      tag_keywords: ["tag"]
#      friend_keywords: ["friend", "friends"]
#      number_keywords:
#        1: ["one", "1", "a", "your"]
#        2: ["two", "2"]
#        3: ["three", "3"]
#        4: ["four", "4"]
#
#  scheduler:
#    search_interval: 5400
#    retweet_interval: 600
#    retweet_random_margin: 60
#    blocked_users_update_interval: 300
#    clear_queue_interval: 60
#    rate_limit_update_interval: 60
#    check_mentions_interval: 600
#
#notifiers:
#  pushbullet:
#    enabled: false
#    token: my_pushbullet_token
#  mail:
#    enabled: false
#    host: smtp.provider.com
#    port: 25
#    tls: false
#    username: sender_address@provider.com
#    password: my_secure_password
#    recipient: sender_address@provider.com


